# -*- coding: utf-8 -*-
# P7 汇总报告完整性校验
import os, re
from collections import Counter
from openpyxl import load_workbook

BASE = r"e:\zt\ggz\研发部\3.7项目\需求分析\PA-替代需求"
RPT = os.path.join(BASE, "deliverables-summary", "deliverables-summary.html")

ok = True
def check(name, cond, detail=""):
    global ok
    if not cond:
        ok = False
    print(f"[{'PASS' if cond else 'FAIL'}] {name} {detail}")

# 1) 文件存在
for f in ["deliverables-summary.html", r"assets\charts.js", r"_shared\js\echarts.min.js", r"_shared\fonts\JetBrainsMono-Regular.ttf"]:
    p = os.path.join(BASE, "deliverables-summary", f)
    check(f"文件存在 {f}", os.path.exists(p))

html = open(RPT, encoding="utf-8").read()
js = open(os.path.join(BASE, "deliverables-summary", "assets", "charts.js"), encoding="utf-8").read()

# 2) 结构
check("首行注释头", html.startswith("<!-- Generated by Trae Work -->"))
check("echarts 引用", './_shared/js/echarts.min.js' in html)
check("charts.js 引用", 'src="assets/charts.js"' in html)
check("无 CDN/绝对路径", not re.search(r'https?://cdn|file:///', html))
check("图表标题齐备", html.count('<figcaption>') == 3)
check("图表容器齐备", all(f'id="chart-{n}"' in html for n in ['cat-rate', 'support', 'diff']))
check("无内联图表脚本", '<script>' not in html)

# 3) 工作簿真实数据
wb = load_workbook(os.path.join(BASE, "天融信vsPA功能对比.xlsx"), data_only=True)
mx = wb['功能对比矩阵']
n_pts, ts, pa, diff = 0, Counter(), Counter(), Counter()
for r in range(4, mx.max_row + 1):
    c2 = str(mx.cell(r, 2).value or '').strip()
    tsv = str(mx.cell(r, 5).value or '').strip()
    if c2 and tsv:
        n_pts += 1
        ts[tsv] += 1
        pa[str(mx.cell(r, 7).value or '').strip()] += 1
        diff[str(mx.cell(r, 9).value or '').strip()] += 1
check("矩阵 139", n_pts == 139, f'实际{n_pts}')
check("TS 94/19/15/11", (ts['完全支持'], ts['部分支持'], ts['待验证'], ts['不支持']) == (94, 19, 15, 11))
check("PA 101/10/12/10/6", (pa['完全支持'], pa['需订阅授权'], pa['部分支持'], pa['不支持'], pa['待验证']) == (101, 10, 12, 10, 6))
check("差异七类合计 139", sum(diff.values()) == 139, str(dict(diff)))

# 4) 报告数字与图表数据一致
for token in ['94', '19', '15', '11', '101', '12', '10', '6', '46', '31', '25', '17', '16', '2']:
    check(f"js 含 {token}", token in js)
for rate in ['90.6', '68.4', '90.9', '70.0', '42.9', '66.7', '38.5', '78.1', '84.2', '59.1', '60.0', '71.4', '95.2', '69.2', '25.0']:
    check(f"js 支持率 {rate}", rate in js)

# 5) 关键陈述
check("待交付=16 已修正", '待交付</td><td class="num">16' in html)
check("22条仅存于修正记录", len(re.findall(r'22 条', html)) == 2 and '「待交付 22 条」→ 16 条' in html)
check("高优14项表存在", 'V12' in html and 'V91' in html)
check("缺口 R2/R3/R4/R25", all(x in html for x in ['R2', 'R3', 'R4', 'R25']))
check("验证方式分布", '资料补查 42' in html and 'T7' in html)
check("来源列表", html.count('id="cite-') == 5)

print("\n总计:", "ALL PASS" if ok else "HAS FAIL")
